package com.lcwd.user.service.entities;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import com.fasterxml.jackson.annotation.JsonProperty;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Rating {

    @JsonProperty("ratingId")
    private String ratingid;

    @JsonProperty("userId")
    private String userid;

    @JsonProperty("hotelId")
    private String hotelid;

    private int rating;
    private String feedback;
    private Hotel hotel;

    // Getters and setters are generated by Lombok
}
